<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <a class="navbar-brand" href="/">
        <img src="/images/spruit.png" style="max-height: 40px;"/>
        Basisschool de Blije Spruit</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Start <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/?page=user">Gebruikers</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Cijfers
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="/?page=grade">Cijfers toevoegen</a>
                    <a class="dropdown-item" href="/?page=grade&action=show">Cijfers tonen</a>
                </div>
            </li>
        </ul>
    </div>
</nav>