<!-- Load the header -->
<?php require_once('../views/layouts/header.phtml'); ?>

<!-- Start of the page -->
<div class="row">
    <div class="col-12">
        <h3>Openbare Basisschool "De Blije Spruit"</h3>
    </div>
    <div class="col-2">
        <img src="/images/spruit.png" width="100%" />
    </div>
    <div class="col-7">
        Dit is het interne beheer portaal van basisschool de Blije Spruit. <br />
        Je kan hier van alles doen, succes!
        <br /><br />
    </div>
    <div class="col-12">
        <h5>Dat vinden wij niet raar, dat vinden wij alleen maar heel bijzonder....</h5>
    </div>
</div>


<!-- Load the footer -->
<?php require_once('../views/layouts/footer.phtml'); ?>