<!-- Load the header -->
<?php require_once('../views/layouts/header.phtml'); ?>

<!-- Start of the page -->
<h3>Maak een gebruiker</h3>

<div class="col-6">
    <form method="post" action="/?page=user&action=store">
        <div class="row">
            <div class="form-group col-6">
                <label for="firstname">Voornaam</label>
                <input required type="text" name="firstname" class="form-control"/>
            </div>
            <div class="form-group col-6">
                <label for="lastname">Achternaam</label>
                <input required type="text" name="lastname" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                <label for="class">Klas/groep</label>
                <select required name="class" id="class" class="form-control">
                    <?php foreach ($groups AS $group) { ?>
                        <option value="<?= $group ?>"><?= $group ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-6">
                <label for="date_of_birth">Geboorte datum</label>
                <input required type="date" name="date_of_birth" class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-6">
                <label for="class">Klas/groep</label>
                <select required name="education" id="education" class="form-control">
                    <option disabled selected value=""> - Kies - </option>
                    <?php foreach ($educations AS $education) { ?>
                        <option
                            value="<?=$education->id?>"><?=$education->name?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-6">
                <label for="role">role</label>
                <select required name="role" id="role" class="form-control">
                    <option disabled selected value=""> - Kies - </option>
                    <?php foreach ($roles AS $role) { ?>
                        <option
                                value="<?=$role->id?>"><?=$role->name?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-3">
                <button class="form-control btn btn-sm btn-outline-primary">Opslaan</button>
            </div>
        </div>
    </form>
</div>

<!-- Load the footer -->
<?php require_once('../views/layouts/footer.phtml'); ?>