<!-- Load the header -->
<?php require_once('../views/layouts/header.phtml'); ?>

<!-- Start of the page -->
<h3>Cijfer bewerken van <?= $usg->user()->firstname ?>  <?= $usg->user()->lastname ?> voor vak  <?= $usg->course()->name ?></h3>

<div class="col-6">
    <form method="post" action="/?page=grade&action=update">
        <input type="hidden" name="usg_id" value="<?= $usg->id ?>" />
        <div class="form-group">
            <label for="grade">Cijfer</label>
            <select required name="grade" class="form-control">
                <?php for ($i = 10; $i >= 1; $i--) { ?>
                    <?php if($i == $usg->grade) {?>
                        <option value="<?= $i ?>" selected><?= $i ?></option>
                    <?php }else{ ?>
                        <option value="<?= $i ?>"><?= $i ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
        </div>

        <div class="form-group col-3">
            <button class="form-control btn btn-sm btn-outline-primary">Opslaan</button>
        </div>
    </form>
</div>

<!-- Load the footer -->
<?php require_once('../views/layouts/footer.phtml'); ?>
