<!-- Load the header -->
<?php require_once('../views/layouts/header.phtml'); ?>

<!-- Start of the page -->
<h3>Kies een klas</h3>
Voor welke klas en welk vak wil je cijfers invoeren?

<div class="col-6">
    <form method="post" action="/?page=grade&action=create">
        <div class="row">
            <div class="form-group col-6">
                <label for="class">Groep</label>
                <select class="form-control" name="class" id="class">
                    <?php foreach ($classes AS $class) { ?>
                    <option value="<?= $class ?>">Groep <?= $class ?></option>
                    <?php } ?>
                </select>
            </div>
            <div class="form-group col-6">
                <label for="course">Vak</label>
                <select class="form-control" name="course" id="course">
                    <?php foreach ($courses AS $course) { ?>
                        <option value="<?= $course->id ?>"><?= $course->name ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-3">
                <button class="form-control btn btn-sm btn-outline-primary">Cijfers invoeren</button>
            </div>
        </div>
    </form>
</div>

<!-- Load the footer -->
<?php require_once('../views/layouts/footer.phtml'); ?>